### ISSUE TITLE
[FxiOS] Launch the survey surface at startup

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12847]
At startup of the app, before the app is usable, check for a message from `GleanPlumbMessagingManager.shared.getNextMessage(for: .survey)`.

If this is not nil, then the survey surface should be displayed.

For development purposes the following message should be displayed once.

```yaml
      - channel: developer
        value:
          messages:
            survey-surface-validation-message:
              title: User research test
              text: Please help Firefox by taking this short survey
              button-label: Take Survey
              action: https://example.com
              surface: survey
              style: SURVEY
              trigger:
                - ALWAYS
```

The tapping of the button should dismiss the surface, and launch a new tab containing `https://example.com`

Additional testing:

* change the action to `OPEN_SETTINGS` Tapping on the button should open the settings page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5525)
