### ISSUE TITLE
[Analytics] Add Telemetry for the Confirmation View

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#20800]
```
confirmation_shown:
    type: event
    description: |
        Records that the confirmation message in the survey has been viewed by the user.
    bugs:
      - https://github.com/mozilla-mobile/firefox-ios/issues/xxxxx
    data_reviews:
      - https://github.com/mozilla-mobile/firefox-ios/pull/xxxxx
    notification_emails:
      - fx-ios-data-stewards@mozilla.com
    expires: "2025-01-01"
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9393)
