### ISSUE TITLE
Telemetry For Password Generator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#21248]
```
password_generator:
  shown:
    type: counter
    description: |
        The password generator bottom sheet was shown and is visible
    bugs:
      - https://github.com/mozilla-mobile/firefox-ios/issues/21248
    data_reviews:
      - https://github.com/mozilla-mobile/firefox-ios/issues/21248
    notification_emails:
      - fx-ios-data-stewards@mozilla.com
    expires: "2025-01-01"
  filled:
    type: counter
    description: |
        The "Use Password" button of the password generator bottom sheet was clicked.
    bugs:
      - https://github.com/mozilla-mobile/firefox-ios/issues/21248
    data_reviews:
      - https://github.com/mozilla-mobile/firefox-ios/issues/21248
    notification_emails:
      - fx-ios-data-stewards@mozilla.com
    expires: "2025-01-01"
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9646)
