### ISSUE TITLE
Add back Labeled Quantity for Tabs counts telemetry now that it is implemented on Glean

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#27075]
```yaml
user.tabs:
  tab_counts:
    type: labeled_quantity
    description: |
      the number of tabs that a user has (normal, private, inactive, and total)
    labels:
      - normal_count
      - private_count
      - inactive_count
      - total_count
    bugs:
      - https://github.com/mozilla-mobile/firefox-ios/issues/9627
      - new bug
    data_reviews:
      - https://github.com/mozilla-mobile/firefox-ios/pull/10272
      - https://github.com/mozilla-mobile/firefox-ios/pull/12334
      - https://github.com/mozilla-mobile/firefox-ios/pull/14102
      - new data review
    notification_emails:
      - fx-ios-data-stewards@mozilla.com
    expires: "2025-07-01" 
    unit: quantity of inactive tabs
    metadata:
      tags:
        - TabsPanel
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-12421)
